version: '3.8'

networks:
  saber_network:

services:
  backend:
    build: .
    container_name: saber_backend
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8008:8000"
    env_file:
      - .env.dev
    networks:
      - saber_network
    restart: on-failure
